---
title: "'Exit Try' può essere specificato solo all'interno di un'istruzione 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 5280b041f1219ab9577e684c0814c13821ed9de0
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 06/04/2020
ms.locfileid: "84397116"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' può essere specificato solo all'interno di un'istruzione 'Try'
`Exit Try` può trovarsi solo all'interno di un'istruzione del blocco `Try` . È presente un'istruzione `Exit Try` ridondante oppure l'istruzione `Exit Try` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30393  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1. Individuare e rimuovere l'istruzione `Exit Try` non necessaria.  
  
2. Spostare l' `Exit Try` istruzione nella posizione appropriata all'interno del codice.  
  
## <a name="see-also"></a>Vedere anche

- [Istruzione Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
