---
title: Gestione degli errori di I/O in .NET
description: Informazioni su come gestire gli errori di I/O in .NET. Eseguire il mapping di codici di errore alle eccezioni, gestire le eccezioni nelle operazioni di I/O e gestire IOException.
ms.date: 08/27/2018
ms.technology: dotnet-standard
dev_langs:
- csharp
- vb
helpviewer_keywords:
- I/O, exception handling
- I/O, errors
ms.workload:
- dotnet
- dotnetcore
ms.openlocfilehash: 45f3951b727d3b615d8384541ff169e8840acab0
ms.sourcegitcommit: cdb295dd1db589ce5169ac9ff096f01fd0c2da9d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 06/09/2020
ms.locfileid: "84599802"
---
# <a name="handling-io-errors-in-net"></a><span data-ttu-id="656d4-104">Gestione degli errori di I/O in .NET</span><span class="sxs-lookup"><span data-stu-id="656d4-104">Handling I/O errors in .NET</span></span>

<span data-ttu-id="656d4-105">Oltre alle eccezioni che possono essere generate in qualsiasi chiamata a un metodo (ad esempio, <xref:System.OutOfMemoryException> quando un sistema è in sovraccarico o <xref:System.NullReferenceException> a causa di un errore del programmatore), i metodi del file system .NET possono generare le eccezioni seguenti:</span><span class="sxs-lookup"><span data-stu-id="656d4-105">In addition to the exceptions that can be thrown in any method call (such as an <xref:System.OutOfMemoryException> when a system is stressed or an <xref:System.NullReferenceException> due to programmer error), .NET file system methods can throw the following exceptions:</span></span>

- <span data-ttu-id="656d4-106"><xref:System.IO.IOException?displayProperty=nameWithType>, la classe di base di tutti i tipi di eccezioni <xref:System.IO>.</span><span class="sxs-lookup"><span data-stu-id="656d4-106"><xref:System.IO.IOException?displayProperty=nameWithType>, the base class of all <xref:System.IO> exception types.</span></span> <span data-ttu-id="656d4-107">Viene generata per gli errori i cui codici restituiti dal sistema operativo non eseguono il mapping diretto a nessun altro tipo di eccezione.</span><span class="sxs-lookup"><span data-stu-id="656d4-107">It is thrown for errors whose return codes from the operating system don't directly map to any other exception type.</span></span>
- <span data-ttu-id="656d4-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="656d4-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="656d4-114"><xref:System.ArgumentException?displayProperty=nameWithType>, generata per i caratteri non validi nel percorso in .NET Framework e in .NET Core 2.0 e versioni precedenti.</span><span class="sxs-lookup"><span data-stu-id="656d4-114"><xref:System.ArgumentException?displayProperty=nameWithType>, which is thrown for invalid path characters on .NET Framework and on .NET Core 2.0 and previous versions.</span></span>
- <span data-ttu-id="656d4-115"><xref:System.NotSupportedException?displayProperty=nameWithType>, generata per i caratteri due punti non validi in .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="656d4-115"><xref:System.NotSupportedException?displayProperty=nameWithType>, which is thrown for invalid colons in .NET Framework.</span></span>
- <span data-ttu-id="656d4-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>, generata per le applicazioni in esecuzione con attendibilità limitata senza le autorizzazioni necessarie solo in .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="656d4-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>, which is thrown for applications running in limited trust that lack the necessary permissions on .NET Framework only.</span></span> <span data-ttu-id="656d4-117">L'attendibilità totale è l'impostazione predefinita in .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="656d4-117">(Full trust is the default on .NET Framework.)</span></span>

## <a name="mapping-error-codes-to-exceptions"></a><span data-ttu-id="656d4-118">Mapping dei codici di errore alle eccezioni</span><span class="sxs-lookup"><span data-stu-id="656d4-118">Mapping error codes to exceptions</span></span>

<span data-ttu-id="656d4-119">Poiché il file system è una risorsa del sistema operativo, i metodi di I/O sia in .NET Core che in .NET eseguono il wrapping delle chiamate nel sistema operativo sottostante.</span><span class="sxs-lookup"><span data-stu-id="656d4-119">Because the file system is an operating system resource, I/O methods in both .NET Core and .NET Framework wrap calls to the underlying operating system.</span></span> <span data-ttu-id="656d4-120">Quando si verifica un errore di I/O nel codice eseguito dal sistema operativo, il sistema operativo restituisce le informazioni sull'errore al metodo di I/O di .NET.</span><span class="sxs-lookup"><span data-stu-id="656d4-120">When an I/O error occurs in code executed by the operating system, the operating system returns error information to the .NET I/O method.</span></span> <span data-ttu-id="656d4-121">Il metodo converte quindi le informazioni sull'errore, in genere in formato codice di errore, in un tipo di eccezione .NET.</span><span class="sxs-lookup"><span data-stu-id="656d4-121">The method then translates the error information, typically in the form of an error code, into a .NET exception type.</span></span> <span data-ttu-id="656d4-122">Nella maggior parte dei casi, esegue questa operazione convertendo direttamente il codice di errore nel tipo di eccezione corrispondente, senza eseguire mapping specifici dell'errore basati sul contesto della chiamata al metodo.</span><span class="sxs-lookup"><span data-stu-id="656d4-122">In most cases, it does this by directly translating the error code into its corresponding exception type; it does not perform any special mapping of the error based on the context of the method call.</span></span>

<span data-ttu-id="656d4-123">Nel sistema operativo Windows, ad esempio, una chiamata a un metodo che restituisce un codice di errore `ERROR_FILE_NOT_FOUND` (o 0x02) esegue il mapping a <xref:System.IO.FileNotFoundException> e un codice di errore `ERROR_PATH_NOT_FOUND` (o 0x03) esegue il mapping a <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="656d4-123">For example, on the Windows operating system, a method call that returns an error code of `ERROR_FILE_NOT_FOUND` (or 0x02) maps to a <xref:System.IO.FileNotFoundException>, and an error code of `ERROR_PATH_NOT_FOUND` (or 0x03) maps to a <xref:System.IO.DirectoryNotFoundException>.</span></span>

<span data-ttu-id="656d4-124">Tuttavia, le condizioni esatte in cui il sistema operativo restituisce determinati codici di errore spesso sono poco o per nulla documentate.</span><span class="sxs-lookup"><span data-stu-id="656d4-124">However, the precise conditions under which the operating system returns particular error codes is often undocumented or poorly documented.</span></span> <span data-ttu-id="656d4-125">Possono quindi verificarsi eccezioni impreviste.</span><span class="sxs-lookup"><span data-stu-id="656d4-125">As a result, unexpected exceptions can occur.</span></span> <span data-ttu-id="656d4-126">Poiché ad esempio si usa una directory invece di un file, se si fornisse un percorso di directory non valido al costruttore <xref:System.IO.DirectoryInfo.%23ctor%2A>, dovrebbe essere generata un'eccezione <xref:System.IO.DirectoryNotFoundException>,</span><span class="sxs-lookup"><span data-stu-id="656d4-126">For example, because you are working with a directory rather than a file, you would expect that providing an invalid directory path to the <xref:System.IO.DirectoryInfo.%23ctor%2A> constructor throws a <xref:System.IO.DirectoryNotFoundException>.</span></span> <span data-ttu-id="656d4-127">ma potrebbe anche venire generata un'eccezione <xref:System.IO.FileNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="656d4-127">However, it may also throw a <xref:System.IO.FileNotFoundException>.</span></span>

## <a name="exception-handling-in-io-operations"></a><span data-ttu-id="656d4-128">Gestione delle eccezioni nelle operazioni di I/O</span><span class="sxs-lookup"><span data-stu-id="656d4-128">Exception handling in I/O operations</span></span>

<span data-ttu-id="656d4-129">A causa di questa dipendenza dal sistema operativo, con condizioni di eccezione identiche (come l'errore di directory non trovata dell'esempio) un metodo di I/O può generare una qualsiasi tra tutte le eccezioni di I/O della classe.</span><span class="sxs-lookup"><span data-stu-id="656d4-129">Because of this reliance on the operating system, identical exception conditions (such as the directory not found error in our example) can result in an I/O method throwing any one of the entire class of I/O exceptions.</span></span> <span data-ttu-id="656d4-130">Pertanto, quando si chiamano le API di I/O, il codice deve essere preparato per gestire tutte o quasi tutte le eccezioni, come illustrato nella tabella seguente:</span><span class="sxs-lookup"><span data-stu-id="656d4-130">This means that, when calling I/O APIs, your code should be prepared to handle most or all of these exceptions, as shown in the following table:</span></span>

| <span data-ttu-id="656d4-131">Tipo di eccezione</span><span class="sxs-lookup"><span data-stu-id="656d4-131">Exception type</span></span> | <span data-ttu-id="656d4-132">.NET Core</span><span class="sxs-lookup"><span data-stu-id="656d4-132">.NET Core</span></span> | <span data-ttu-id="656d4-133">.NET Framework</span><span class="sxs-lookup"><span data-stu-id="656d4-133">.NET Framework</span></span> |
|---|---|---|
| <xref:System.IO.IOException> | <span data-ttu-id="656d4-134">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-134">Yes</span></span> | <span data-ttu-id="656d4-135">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-135">Yes</span></span> |
| <xref:System.IO.FileNotFoundException> | <span data-ttu-id="656d4-136">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-136">Yes</span></span> | <span data-ttu-id="656d4-137">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-137">Yes</span></span> |
| <xref:System.IO.DirectoryNotFoundException> | <span data-ttu-id="656d4-138">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-138">Yes</span></span> | <span data-ttu-id="656d4-139">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-139">Yes</span></span> |
| <xref:System.IO.DriveNotFoundException?> | <span data-ttu-id="656d4-140">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-140">Yes</span></span> | <span data-ttu-id="656d4-141">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-141">Yes</span></span> |
| <xref:System.IO.PathTooLongException> | <span data-ttu-id="656d4-142">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-142">Yes</span></span> | <span data-ttu-id="656d4-143">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-143">Yes</span></span> |
| <xref:System.OperationCanceledException> | <span data-ttu-id="656d4-144">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-144">Yes</span></span> | <span data-ttu-id="656d4-145">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-145">Yes</span></span> |
| <xref:System.UnauthorizedAccessException> | <span data-ttu-id="656d4-146">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-146">Yes</span></span> | <span data-ttu-id="656d4-147">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-147">Yes</span></span> |
| <xref:System.ArgumentException> | <span data-ttu-id="656d4-148">.NET Core 2.0 e versioni precedenti</span><span class="sxs-lookup"><span data-stu-id="656d4-148">.NET Core 2.0 and earlier</span></span>| <span data-ttu-id="656d4-149">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-149">Yes</span></span> |
| <xref:System.NotSupportedException> | <span data-ttu-id="656d4-150">No</span><span class="sxs-lookup"><span data-stu-id="656d4-150">No</span></span> | <span data-ttu-id="656d4-151">Sì</span><span class="sxs-lookup"><span data-stu-id="656d4-151">Yes</span></span> |
| <xref:System.Security.SecurityException> | <span data-ttu-id="656d4-152">No</span><span class="sxs-lookup"><span data-stu-id="656d4-152">No</span></span> | <span data-ttu-id="656d4-153">Solo attendibilità limitata</span><span class="sxs-lookup"><span data-stu-id="656d4-153">Limited trust only</span></span> |

## <a name="handling-ioexception"></a><span data-ttu-id="656d4-154">Gestione di IOException</span><span class="sxs-lookup"><span data-stu-id="656d4-154">Handling IOException</span></span>

<span data-ttu-id="656d4-155">In quanto classe di base per le eccezioni nello spazio dei nomi <xref:System.IO>, viene generata un'eccezione <xref:System.IO.IOException> anche per i codici di errore che non eseguono il mapping a un tipo di eccezione predefinito.</span><span class="sxs-lookup"><span data-stu-id="656d4-155">As the base class for exceptions in the <xref:System.IO> namespace, <xref:System.IO.IOException> is also thrown for any error code that does not map to a predefined exception type.</span></span> <span data-ttu-id="656d4-156">Può essere quindi generata da qualsiasi operazione di I/O.</span><span class="sxs-lookup"><span data-stu-id="656d4-156">This means that it can be thrown by any I/O operation.</span></span>

> [!IMPORTANT]
> <span data-ttu-id="656d4-157">Poiché <xref:System.IO.IOException> è la classe di base degli altri tipi di eccezioni nello spazio dei nomi <xref:System.IO>, è consigliabile gestire un blocco `catch` dopo aver gestito le altre eccezioni relative alle operazioni di I/O.</span><span class="sxs-lookup"><span data-stu-id="656d4-157">Because <xref:System.IO.IOException> is the base class of the other exception types in the <xref:System.IO> namespace, you should handle in a `catch` block after you've handled the other I/O-related exceptions.</span></span>

<span data-ttu-id="656d4-158">Inoltre, a partire da .NET Core 2.1, i controlli di convalida della correttezza del percorso (ad esempio, per assicurarsi che in un percorso non siano presenti caratteri non validi) sono stati rimossi e il runtime genera un'eccezione di cui viene eseguito il mapping da un codice di errore del sistema operativo invece che dal proprio codice di convalida.</span><span class="sxs-lookup"><span data-stu-id="656d4-158">In addition, starting with .NET Core 2.1, validation checks for path correctness (for example, to ensure that invalid characters are not present in a path) have been removed, and the runtime throws an exception mapped from an operating system error code rather than from its own validation code.</span></span> <span data-ttu-id="656d4-159">In questo caso l'eccezione che viene generata con maggior probabilità è <xref:System.IO.IOException>, ma potrebbe essere generato qualsiasi altro tipo di eccezione.</span><span class="sxs-lookup"><span data-stu-id="656d4-159">The most likely exception to be thrown in this case is an <xref:System.IO.IOException>, although any other exception type could also be thrown.</span></span>

<span data-ttu-id="656d4-160">Si noti che nel codice di gestione dell'eccezione, si dovrà gestire sempre per ultima <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="656d4-160">Note that, in your exception handling code, you should always handle the <xref:System.IO.IOException> last.</span></span> <span data-ttu-id="656d4-161">In caso contrario, poiché si tratta della classe di base di tutte le altre eccezioni di I/O, i blocchi catch di classi derivate non verranno valutati.</span><span class="sxs-lookup"><span data-stu-id="656d4-161">Otherwise, because it is the base class of all other IO exceptions, the catch blocks of derived classes will not be evaluated.</span></span>

<span data-ttu-id="656d4-162">Nel caso di <xref:System.IO.IOException>, è possibile ottenere altre informazioni sull'errore dalla proprietà [IOException.HResult](xref:System.Exception.HResult).</span><span class="sxs-lookup"><span data-stu-id="656d4-162">In the case of an <xref:System.IO.IOException>, you can get additional error information from the [IOException.HResult](xref:System.Exception.HResult) property.</span></span> <span data-ttu-id="656d4-163">Per convertire il valore HResult in un codice di errore Win32, si rimuovono i 16 bit superiori del valore da 32 bit.</span><span class="sxs-lookup"><span data-stu-id="656d4-163">To convert the HResult value to a Win32 error code, you strip out the upper 16 bits of the 32-bit value.</span></span> <span data-ttu-id="656d4-164">La tabella seguente elenca i codici di errore di cui potrebbe essere eseguito il wrapping in un'eccezione <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="656d4-164">The following table lists error codes that may be wrapped in an <xref:System.IO.IOException>.</span></span>

| <span data-ttu-id="656d4-165">HResult</span><span class="sxs-lookup"><span data-stu-id="656d4-165">HResult</span></span> | <span data-ttu-id="656d4-166">Costante</span><span class="sxs-lookup"><span data-stu-id="656d4-166">Constant</span></span> | <span data-ttu-id="656d4-167">Descrizione</span><span class="sxs-lookup"><span data-stu-id="656d4-167">Description</span></span> |
| --- | --- | --- |
| <span data-ttu-id="656d4-168">ERROR_SHARING_VIOLATION</span><span class="sxs-lookup"><span data-stu-id="656d4-168">ERROR_SHARING_VIOLATION</span></span> | <span data-ttu-id="656d4-169">32</span><span class="sxs-lookup"><span data-stu-id="656d4-169">32</span></span> | <span data-ttu-id="656d4-170">Il nome del file è mancante oppure il file o la directory è in uso.</span><span class="sxs-lookup"><span data-stu-id="656d4-170">The file name is missing, or the file or directory is in use.</span></span> |
| <span data-ttu-id="656d4-171">ERROR_FILE_EXISTS</span><span class="sxs-lookup"><span data-stu-id="656d4-171">ERROR_FILE_EXISTS</span></span> | <span data-ttu-id="656d4-172">80</span><span class="sxs-lookup"><span data-stu-id="656d4-172">80</span></span> | <span data-ttu-id="656d4-173">File già esistente.</span><span class="sxs-lookup"><span data-stu-id="656d4-173">The file already exists.</span></span> |
| <span data-ttu-id="656d4-174">ERROR_INVALID_PARAMETER</span><span class="sxs-lookup"><span data-stu-id="656d4-174">ERROR_INVALID_PARAMETER</span></span> | <span data-ttu-id="656d4-175">87</span><span class="sxs-lookup"><span data-stu-id="656d4-175">87</span></span> | <span data-ttu-id="656d4-176">Un argomento fornito al metodo non è valido.</span><span class="sxs-lookup"><span data-stu-id="656d4-176">An argument supplied to the method is invalid.</span></span> |
| <span data-ttu-id="656d4-177">ERROR_ALREADY_EXISTS</span><span class="sxs-lookup"><span data-stu-id="656d4-177">ERROR_ALREADY_EXISTS</span></span> | <span data-ttu-id="656d4-178">183</span><span class="sxs-lookup"><span data-stu-id="656d4-178">183</span></span> | <span data-ttu-id="656d4-179">File o directory già esistente.</span><span class="sxs-lookup"><span data-stu-id="656d4-179">The file or directory already exists.</span></span> |

<span data-ttu-id="656d4-180">È possibile gestirli usando una clausola `When` in un'istruzione catch, come illustrato nell'esempio seguente.</span><span class="sxs-lookup"><span data-stu-id="656d4-180">You can handle these using a `When` clause in a catch statement, as the following example shows.</span></span>

[!code-csharp[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/cs/io-exceptions.cs)]
[!code-vb[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/vb/io-exceptions.vb)]

## <a name="see-also"></a><span data-ttu-id="656d4-181">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="656d4-181">See also</span></span>

- [<span data-ttu-id="656d4-182">Gestione e generazione di eccezioni in .NET</span><span class="sxs-lookup"><span data-stu-id="656d4-182">Handling and throwing exceptions in .NET</span></span>](../exceptions/index.md)
- [<span data-ttu-id="656d4-183">Gestione delle eccezioni (Task Parallel Library)</span><span class="sxs-lookup"><span data-stu-id="656d4-183">Exception handling (Task Parallel Library)</span></span>](../parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="656d4-184">Procedure consigliate per le eccezioni</span><span class="sxs-lookup"><span data-stu-id="656d4-184">Best practices for exceptions</span></span>](../exceptions/best-practices-for-exceptions.md)
- [<span data-ttu-id="656d4-185">Come usare eccezioni specifiche in un blocco catch</span><span class="sxs-lookup"><span data-stu-id="656d4-185">How to use specific exceptions in a catch block</span></span>](../exceptions/how-to-use-specific-exceptions-in-a-catch-block.md)
